// Reports & export screen (رپورٹ و ایکسپورٹ).
//
// CSV exports are generated by pure functions in export_service.dart;
// the PDF farm report and party receipts are rendered from real Flutter
// widgets captured as images (pdf_report_service.dart) so Urdu shaping
// is exactly as correct as on screen.
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';
import 'package:share_plus/share_plus.dart';

import '../models/batai.dart';
import '../models/models.dart';
import '../models/party.dart';
import '../providers/activity_provider.dart';
import '../providers/batai_provider.dart';
import '../providers/crop_provider.dart';
import '../providers/expense_provider.dart';
import '../providers/farm_provider.dart';
import '../providers/harvest_provider.dart';
import '../providers/inventory_provider.dart';
import '../providers/party_provider.dart';
import '../providers/ushr_provider.dart';
import '../services/export_service.dart';
import '../services/money.dart';
import '../services/pdf_report_service.dart';
import '../services/pnl_summary.dart';
import '../widgets/report_widgets.dart';

class ReportsScreen extends StatefulWidget {
  const ReportsScreen({super.key});

  @override
  State<ReportsScreen> createState() => _ReportsScreenState();
}

class _ReportsScreenState extends State<ReportsScreen> {
  bool _loadingCounts = true;
  int _expenseCount = 0;
  int _saleCount = 0;
  int _partyEntryCount = 0;
  int _txnCount = 0;
  int _settlementCount = 0;
  bool _busy = false;

  @override
  void initState() {
    super.initState();
    _loadCounts();
  }

  Future<void> _loadCounts() async {
    final expenseProvider = context.read<ExpenseProvider>();
    final harvestProvider = context.read<HarvestProvider>();
    final partyProvider = context.read<PartyProvider>();
    final inventoryProvider = context.read<InventoryProvider>();
    final bataiProvider = context.read<BataiProvider>();
    try {
      int partyEntries = 0;
      for (final p in partyProvider.parties) {
        if (p.id != null) {
          partyEntries += (await partyProvider.getEntries(p.id!)).length;
        }
      }
      int txns = 0;
      for (final item in inventoryProvider.inventoryList) {
        if (item.id != null) {
          txns += (await inventoryProvider.getTransactions(item.id!)).length;
        }
      }
      int settlements = 0;
      for (final a in bataiProvider.agreements) {
        if (a.agreement.id != null) {
          settlements +=
              (await bataiProvider.getSettlements(a.agreement.id!)).length;
        }
      }
      if (!mounted) return;
      setState(() {
        _expenseCount = expenseProvider.expenses.length;
        _saleCount =
            harvestProvider.harvests.where((h) => h.sale != null).length;
        _partyEntryCount = partyEntries;
        _txnCount = txns;
        _settlementCount = settlements;
        _loadingCounts = false;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() => _loadingCounts = false);
      _snack('تعداد لوڈ کرنے میں خرابی', Colors.red);
    }
  }

  void _snack(String msg, Color color) {
    if (!mounted) return;
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(SnackBar(content: Text(msg), backgroundColor: color));
  }

  String _stamp() => DateFormat('yyyyMMdd_HHmmss').format(DateTime.now());

  Future<void> _saveAndShare(String filename, List<int> bytes) async {
    final docs = await getApplicationDocumentsDirectory();
    final dir = Directory('${docs.path}/exports');
    if (!await dir.exists()) await dir.create(recursive: true);
    final file = File('${dir.path}/$filename');
    await file.writeAsBytes(bytes, flush: true);
    await SharePlus.instance.share(
      ShareParams(files: [XFile(file.path)], text: 'کسان دوست رپورٹ'),
    );
  }

  /// Runs [task] with a blocking Urdu progress dialog; always dismisses it.
  Future<void> _withProgress(String label, Future<void> Function() task) async {
    if (_busy) return;
    setState(() => _busy = true);
    showDialog(
      context: context,
      barrierDismissible: false,
      builder:
          (_) => AlertDialog(
            content: Row(
              children: [
                const CircularProgressIndicator(),
                const SizedBox(width: 16),
                Expanded(child: Text(label)),
              ],
            ),
          ),
    );
    try {
      await task();
    } catch (e) {
      _snack('خرابی: $e', Colors.red);
    } finally {
      if (mounted) Navigator.of(context, rootNavigator: true).pop();
      if (mounted) setState(() => _busy = false);
    }
  }

  // ---------------- CSV exports ----------------

  Future<void> _exportExpensesCsv() =>
      _withProgress('CSV تیار ہو رہا ہے...', () async {
        final expenses = context.read<ExpenseProvider>().expenses;
        final farms = context.read<FarmProvider>().farms;
        final farmNames = {
          for (final f in farms)
            if (f.id != null) f.id!: f.name,
        };
        final fieldNames = <int, String>{};
        for (final f in farms) {
          for (final fld in context.read<FarmProvider>().getFieldsForFarm(
            f.id!,
          )) {
            if (fld.id != null) fieldNames[fld.id!] = fld.name;
          }
        }
        final crops = [
          ...context.read<CropProvider>().activeCropSeasons,
          ...context.read<CropProvider>().harvestedCropSeasons,
        ];
        final cropNames = {
          for (final c in crops)
            if (c.cropSeason.id != null)
              c.cropSeason.id!:
                  '${c.cropSeason.cropName} (${c.cropSeason.variety})',
        };
        final csv = expensesCsv(
          expenses,
          farmNames: farmNames,
          fieldNames: fieldNames,
          cropNames: cropNames,
          categoryLabels: context.read<ExpenseProvider>().expenseCategories,
        );
        await _saveAndShare('kisan_dost_expenses_${_stamp()}.csv', _utf8(csv));
        _snack('اخراجات کی CSV تیار ہے', Colors.green);
      });

  Future<void> _exportSalesCsv() =>
      _withProgress('CSV تیار ہو رہا ہے...', () async {
        final harvests = context.read<HarvestProvider>().harvests;
        final csv = salesCsv(harvests);
        await _saveAndShare('kisan_dost_sales_${_stamp()}.csv', _utf8(csv));
        _snack('فروخت کی CSV تیار ہے', Colors.green);
      });

  Future<void> _exportPartyCsv() => _withProgress(
    'CSV تیار ہو رہا ہے...',
    () async {
      final partyProvider = context.read<PartyProvider>();
      final entries = <PartyLedgerEntry>[];
      for (final p in partyProvider.parties) {
        if (p.id != null) entries.addAll(await partyProvider.getEntries(p.id!));
      }
      entries.sort((a, b) => a.date.compareTo(b.date));
      final csv = partyLedgerCsv(entries, {
        for (final p in partyProvider.parties)
          if (p.id != null) p.id!: p.name,
      }, partyProvider.allBalances);
      await _saveAndShare(
        'kisan_dost_party_ledger_${_stamp()}.csv',
        _utf8(csv),
      );
      _snack('پارٹی کھاتے کی CSV تیار ہے', Colors.green);
    },
  );

  Future<void> _exportInventoryCsv() =>
      _withProgress('CSV تیار ہو رہا ہے...', () async {
        final inventoryProvider = context.read<InventoryProvider>();
        final txns = <InventoryTransaction>[];
        final itemNames = <int, String>{};
        for (final item in inventoryProvider.inventoryList) {
          if (item.id == null) continue;
          itemNames[item.id!] = '${item.name} (${item.unit})';
          txns.addAll(await inventoryProvider.getTransactions(item.id!));
        }
        txns.sort((a, b) => b.date.compareTo(a.date));
        final csv = inventoryTransactionsCsv(txns, itemNames);
        await _saveAndShare('kisan_dost_inventory_${_stamp()}.csv', _utf8(csv));
        _snack('گودام لین دین کی CSV تیار ہے', Colors.green);
      });

  Future<void>
  _exportBataiCsv() => _withProgress('CSV تیار ہو رہا ہے...', () async {
    final bataiProvider = context.read<BataiProvider>();
    final settlements = <BataiSettlement>[];
    final labels = <int, String>{};
    for (final a in bataiProvider.agreements) {
      final id = a.agreement.id;
      if (id == null) continue;
      labels[id] =
          '${a.partyName ?? 'نامعلوم'} — ${a.agreement.ownerSharePercent}/${a.agreement.cultivatorSharePercent}';
      settlements.addAll(await bataiProvider.getSettlements(id));
    }
    settlements.sort((a, b) => a.settleDate.compareTo(b.settleDate));
    final csv = bataiSettlementsCsv(settlements, labels);
    await _saveAndShare('kisan_dost_batai_${_stamp()}.csv', _utf8(csv));
    _snack('بٹائی چکتائیوں کی CSV تیار ہے', Colors.green);
  });

  // ---------------- PDF ----------------

  FarmPnl _gatherPnl() {
    return computeFarmPnl(
      harvests: context.read<HarvestProvider>().harvests,
      totalExpensesPaisa: context.read<ExpenseProvider>().totalExpensesPaisa,
      seasons: [
        ...context.read<CropProvider>().activeCropSeasons,
        ...context.read<CropProvider>().harvestedCropSeasons,
      ],
      activities: context.read<ActivityProvider>().activities,
      expenses: context.read<ExpenseProvider>().expenses,
      ushrRecords: context.read<UshrProvider>().ushrRecords,
    );
  }

  Future<void> _exportPnlPdf(BuildContext captureContext) =>
      _withProgress('PDF رپورٹ تیار ہو رہی ہے...', () async {
        final data = PnlReportData(
          pnl: _gatherPnl(),
          cropNameUrdu: context.read<CropProvider>().predefinedCrops,
          generatedOn: DateFormat('yyyy-MM-dd').format(DateTime.now()),
        );
        final png = await captureReportPng(
          captureContext,
          PnlReportWidget(data: data),
        );
        final pdf = await pngToPdfBytes(png);
        await _saveAndShare('kisan_dost_farm_report_${_stamp()}.pdf', pdf);
        _snack('فارم رپورٹ PDF تیار ہے', Colors.green);
      });

  Future<void> _exportReceiptFlow(BuildContext captureContext) async {
    final partyProvider = context.read<PartyProvider>();
    if (partyProvider.parties.isEmpty) {
      _snack('پہلے کوئی پارٹی شامل کریں', Colors.orange);
      return;
    }
    final party = await showDialog<Party>(
      context: context,
      builder:
          (_) => SimpleDialog(
            title: const Text('پارٹی منتخب کریں'),
            children: [
              for (final p in partyProvider.parties)
                SimpleDialogOption(
                  onPressed: () => Navigator.pop(context, p),
                  child: Text(
                    '${p.name} — ${Money(partyProvider.balanceOf(p.id!)).format()}',
                  ),
                ),
            ],
          ),
    );
    if (party == null || party.id == null || !mounted) return;
    final entries =
        (await partyProvider.getEntries(party.id!))
            .where(
              (e) =>
                  e.type == PartyEntryType.wusooli ||
                  e.type == PartyEntryType.adaigi,
            )
            .toList();
    if (entries.isEmpty) {
      _snack(
        'اس پارٹی کی کوئی ادائیگی (وصولی/ادائیگی) نہیں ملی',
        Colors.orange,
      );
      return;
    }
    if (!mounted) return;
    final entry = await showDialog<PartyLedgerEntry>(
      context: context,
      builder:
          (_) => SimpleDialog(
            title: const Text('رسید کے لیے اندراج منتخب کریں'),
            children: [
              for (final e in entries)
                SimpleDialogOption(
                  onPressed: () => Navigator.pop(context, e),
                  child: Text(
                    '${partyEntryTypeUrdu(e.type)} — ${Money(e.amountPaisa.abs()).format()} — ${e.date}',
                  ),
                ),
            ],
          ),
    );
    if (entry == null || !mounted) return;

    // Running balance AFTER this entry: all entries on/before its date+id.
    final all = await partyProvider.getEntries(party.id!);
    all.sort((a, b) {
      final d = a.date.compareTo(b.date);
      return d != 0 ? d : (a.id ?? 0).compareTo(b.id ?? 0);
    });
    var balance = 0;
    for (final e in all) {
      balance += e.amountPaisa;
      if (e.id == entry.id) break;
    }

    final data = ReceiptData(
      partyName: party.name,
      entry: entry,
      balanceAfterPaisa: balance,
      generatedOn: DateFormat('yyyy-MM-dd').format(DateTime.now()),
    );
    await _withProgress('رسید تیار ہو رہی ہے...', () async {
      final png = await captureReportPng(
        captureContext,
        ReceiptWidget(data: data),
      );
      final pdf = await pngToPdfBytes(png);
      await _saveAndShare('kisan_dost_receipt_${_stamp()}.pdf', pdf);
      _snack('رسید PDF تیار ہے', Colors.green);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('رپورٹ و ایکسپورٹ')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          _sectionTitle('CSV ایکسپورٹ'),
          const SizedBox(height: 4),
          const Text(
            'ایکسل میں کھلنے والی فائلیں — اردو عنوانات کے ساتھ',
            style: TextStyle(color: Colors.grey),
          ),
          const SizedBox(height: 8),
          _csvRow(
            'اخراجات',
            'تمام اخراجات — زمین/کھیت/فصل کے ناموں سمیت',
            _expenseCount,
            _exportExpensesCsv,
            Icons.money_off,
          ),
          _csvRow(
            'فروخت',
            'تمام فروخت — فصل، مقدار اور رقم',
            _saleCount,
            _exportSalesCsv,
            Icons.sell_outlined,
          ),
          _csvRow(
            'پارٹی کھاتہ',
            'تمام اندراجات اور ہر پارٹی کا بیلنس',
            _partyEntryCount,
            _exportPartyCsv,
            Icons.people_outline,
          ),
          _csvRow(
            'گودام لین دین',
            'خریداری، استعمال اور تصحیح کا ریکارڈ',
            _txnCount,
            _exportInventoryCsv,
            Icons.inventory_2_outlined,
          ),
          _csvRow(
            'بٹائی چکتائیاں',
            'ہر معاہدے کی چکتائی اور حصے',
            _settlementCount,
            _exportBataiCsv,
            Icons.handshake_outlined,
          ),
          const SizedBox(height: 20),
          _sectionTitle('PDF رپورٹ'),
          const SizedBox(height: 8),
          Builder(
            builder:
                (captureContext) => Column(
                  children: [
                    Card(
                      child: ListTile(
                        leading: const Icon(
                          Icons.picture_as_pdf_outlined,
                          size: 32,
                          color: Colors.red,
                        ),
                        title: const Text('فارم رپورٹ (PDF)'),
                        subtitle: const Text(
                          'کل آمدنی/اخراجات اور فصل وار منافع و نقصان',
                        ),
                        trailing: const Icon(Icons.share_outlined),
                        onTap:
                            _busy ? null : () => _exportPnlPdf(captureContext),
                      ),
                    ),
                    Card(
                      child: ListTile(
                        leading: const Icon(
                          Icons.receipt_long_outlined,
                          size: 32,
                          color: Colors.teal,
                        ),
                        title: const Text('رسید (PDF)'),
                        subtitle: const Text('پارٹی کی وصولی/ادائیگی کی رسید'),
                        trailing: const Icon(Icons.share_outlined),
                        onTap:
                            _busy
                                ? null
                                : () => _exportReceiptFlow(captureContext),
                      ),
                    ),
                  ],
                ),
          ),
          const SizedBox(height: 24),
        ],
      ),
    );
  }

  Widget _sectionTitle(String t) => Text(
    t,
    style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
  );

  Widget _csvRow(
    String title,
    String subtitle,
    int count,
    VoidCallback onTap,
    IconData icon,
  ) {
    return Card(
      child: ListTile(
        leading: Icon(icon, size: 32, color: Colors.green.shade700),
        title: Text(title),
        subtitle: Text(
          '$subtitle\n${_loadingCounts ? 'گنتی ہو رہی ہے...' : 'ریکارڈ: $count'}',
        ),
        isThreeLine: true,
        trailing: const Icon(Icons.download_outlined),
        onTap: _busy ? null : onTap,
      ),
    );
  }
}

List<int> _utf8(String s) =>
// BOM char (U+FEFF) is already the first char of every CSV — utf8.encode
// emits it as EF BB BF so Excel detects UTF-8.
utf8.encode(s);
